name: rnaseq_takubo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- Alignment ---
  - star=2.7.11b
  - samtools=1.21

  # --- Read counting ---
  - subread=2.0.6

  # --- R and core packages ---
  - r-base=4.5.2
  - bioconductor-deseq2
  - bioconductor-dexseq
  - bioconductor-biocparallel
  - r-tidyverse
  - r-data.table
  - r-ggplot2
  - r-ggrepel
  - r-magrittr
  - r-umap
  - r-yaml
  - r-pheatmap

  # --- fGSEA ---
  - bioconductor-fgsea
  - r-msigdbr

  # --- Utilities ---
  - pigz=2.8
  - wget=1.21.4
