#!/bin/bash
# =============================================================================
# Initialize a New RNA-seq Project
# =============================================================================
# Creates a project directory with the required structure and configuration
# files. The pipeline code itself stays in the cloned repository — this
# script sets up a SEPARATE data/analysis directory.
#
# Usage:
#   bash init_project.sh <project_dir> [genome]
#
# Examples:
#   bash init_project.sh /data/projects/2026_AML_RNAseq hg38
#   bash init_project.sh ~/analysis/Mouse_HSC mm10
#
# The created project directory will contain:
#   config.sh        — project-specific configuration (editable)
#   samples.tsv      — sample sheet template
#   comparisons.tsv  — comparison pairs template (optional)
#   fastq/           — place FASTQ files here
#   Gene_set/        — custom gene sets (copied from pipeline)
# =============================================================================
set -euo pipefail

PIPELINE_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${PIPELINE_DIR}/scripts/utils.sh"

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------
if [[ $# -lt 1 ]]; then
    echo "Usage: bash init_project.sh <project_dir> [genome]"
    echo ""
    echo "  project_dir  Path to the new project directory"
    echo "  genome       Reference genome: hg38 (default) or mm10"
    exit 1
fi

PROJECT_NEW="$(realpath -m "$1")"
GENOME="${2:-hg38}"

if [[ "${GENOME}" != "hg38" && "${GENOME}" != "mm10" ]]; then
    log_error "Unsupported genome: ${GENOME}. Use 'hg38' or 'mm10'."
    exit 1
fi

if [[ -d "${PROJECT_NEW}" ]]; then
    log_error "Directory already exists: ${PROJECT_NEW}"
    log_error "Remove it first or choose a different path."
    exit 1
fi

# ---------------------------------------------------------------------------
# Create directory structure
# ---------------------------------------------------------------------------
log_info "Creating project directory: ${PROJECT_NEW}"
mkdir -p "${PROJECT_NEW}"/{fastq,Gene_set}

# ---------------------------------------------------------------------------
# Generate config.sh (project-specific)
# ---------------------------------------------------------------------------
cat > "${PROJECT_NEW}/config.sh" <<CONFIGEOF
#!/bin/bash
# =============================================================================
# RNA-seq Pipeline Configuration — Project-specific
# =============================================================================
# Generated by init_project.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Pipeline version: $(cat "${PIPELINE_DIR}/VERSION" | tr -d '[:space:]')
# =============================================================================

# --- Pipeline location ---
PIPELINE_DIR="${PIPELINE_DIR}"

# --- Project ---
PROJECT_DIR="${PROJECT_NEW}"
SAMPLES_TSV="\${PROJECT_DIR}/samples.tsv"

# --- Reference Genome ---
GENOME="${GENOME}"

# STAR genome index directory
STAR_INDEX_HG38="\${HOME}/STAR2.7.3/hg38_sjdb149_RefSeq"
STAR_INDEX_MM10="\${HOME}/STAR2.7.3/mm10_sjdb149_RefSeq_ver241129"

# GTF annotation file
GTF_HG38="\${HOME}/Genome/hg38/hg38.ncbiRefSeq.gtf"
GTF_MM10="\${HOME}/Genome/mm10/mm10.ncbiRefSeq.gtf"

# --- STAR mapping parameters ---
STAR_THREADS=6
SJDB_OVERHANG=149
READ_MAP_NUMBER=-1

# --- featureCounts parameters ---
FEATURE_COUNTS_PAIRED=true
FEATURE_COUNTS_MULTI=true
GENE_ATTRIBUTE="gene_name"
EXON_ATTRIBUTE="exon_id"

# --- FASTQ settings ---
FASTQ_DIR="\${PROJECT_DIR}/fastq"

# --- Output directories ---
BAM_DIR="\${PROJECT_DIR}/BAM"
COUNTS_DIR="\${PROJECT_DIR}/counts"
DESEQ2_DIR="\${PROJECT_DIR}/DESeq2"
FGSEA_DIR="\${PROJECT_DIR}/fGSEA"
EXON_DE_DIR="\${PROJECT_DIR}/exon_DE"

# --- DESeq2 parameters ---
MIN_COUNT_FILTER=50
PCA_TOP_GENES=500
VOLCANO_PADJ=0.001
VOLCANO_LOG2FC=1

# --- fGSEA parameters ---
FGSEA_MIN_SIZE=15
FGSEA_MAX_SIZE=500
FGSEA_NPERM=10000
FGSEA_NPROC=12
FGSEA_PADJ=0.05

# --- Gene set files ---
CUSTOM_GMT="\${PROJECT_DIR}/Gene_set/HSC_set3.gmt"

# --- Genes to highlight in volcano plots ---
HIGHLIGHT_GENES="ITGA3,PROCR,KIT,HLF,MECOM,MYCT1,MLLT3,THY1,ADGRG1,CD34"

# =============================================================================
# Derived values (do not edit below this line)
# =============================================================================
if [[ "\${GENOME}" == "hg38" ]]; then
    STAR_INDEX="\${STAR_INDEX_HG38}"
    GTF="\${GTF_HG38}"
    SPECIES="Homo sapiens"
    ORG_DB="org.Hs.eg.db"
elif [[ "\${GENOME}" == "mm10" ]]; then
    STAR_INDEX="\${STAR_INDEX_MM10}"
    GTF="\${GTF_MM10}"
    SPECIES="Mus musculus"
    ORG_DB="org.Mm.eg.db"
else
    echo "ERROR: Unsupported GENOME '\${GENOME}'." >&2
    exit 1
fi
CONFIGEOF

# ---------------------------------------------------------------------------
# Generate samples.tsv template
# ---------------------------------------------------------------------------
cat > "${PROJECT_NEW}/samples.tsv" <<'SAMPLESEOF'
sample_name	group	fq_prefix	lane_suffix
Sample1_pre	pre	Sample1_pre	L5
Sample1_post	post	Sample1_post	L5
Sample2_pre	pre	Sample2_pre	L5
Sample2_post	post	Sample2_post	L5
SAMPLESEOF

# ---------------------------------------------------------------------------
# Generate comparisons.tsv template (optional)
# ---------------------------------------------------------------------------
cat > "${PROJECT_NEW}/comparisons.tsv" <<'COMPEOF'
# Optional: specify comparison pairs explicitly.
# If this file is absent, all pairwise group comparisons are performed.
# Columns: group1 (numerator), group2 (denominator/reference)
group1	group2
post	pre
COMPEOF

# ---------------------------------------------------------------------------
# Copy gene set files
# ---------------------------------------------------------------------------
if [[ -d "${PIPELINE_DIR}/Gene_set" ]]; then
    cp -r "${PIPELINE_DIR}/Gene_set/"* "${PROJECT_NEW}/Gene_set/" 2>/dev/null || true
    log_info "Copied gene set files → ${PROJECT_NEW}/Gene_set/"
fi

# ---------------------------------------------------------------------------
# Copy plot_config.default.yml for visualization customization
# ---------------------------------------------------------------------------
if [[ -f "${PIPELINE_DIR}/plot_config.default.yml" ]]; then
    cp "${PIPELINE_DIR}/plot_config.default.yml" "${PROJECT_NEW}/plot_config.default.yml"
    log_info "Copied plot_config.default.yml → ${PROJECT_NEW}/"
    log_info "個人カスタマイズ: cp plot_config.default.yml plot_config.yml"
fi

# ---------------------------------------------------------------------------
# Create .gitignore for project directory
# ---------------------------------------------------------------------------
cat > "${PROJECT_NEW}/.gitignore" <<'GITEOF'
# Large data files
fastq/
BAM/
*.bam
*.bai
*.fq.gz
*.fastq.gz

# R session
.Rhistory
.RData

# Pipeline lock
.pipeline.lock

# Personal plot config (use plot_config.default.yml as template)
plot_config.yml

# renv library (reproducible via renv.lock)
renv/library/
renv/staging/
renv/sandbox/

# Provenance (auto-generated)
# provenance.yml
GITEOF

# ---------------------------------------------------------------------------
# Initialize git repo in project (optional but recommended)
# ---------------------------------------------------------------------------
if command -v git &>/dev/null; then
    cd "${PROJECT_NEW}"
    git init -q
    git add -A
    git commit -q -m "Initialize RNA-seq project (pipeline v$(cat "${PIPELINE_DIR}/VERSION" | tr -d '[:space:]'))"
    log_info "Git repository initialized in ${PROJECT_NEW}"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "======================================================"
echo "  Project initialized: ${PROJECT_NEW}"
echo "======================================================"
echo ""
echo "Next steps:"
echo "  1. Edit ${PROJECT_NEW}/config.sh"
echo "  2. Edit ${PROJECT_NEW}/samples.tsv"
echo "  3. Place FASTQ files in ${PROJECT_NEW}/fastq/"
echo "  4. (Optional) Customize plots:"
echo "       cp ${PROJECT_NEW}/plot_config.default.yml ${PROJECT_NEW}/plot_config.yml"
echo "       vim ${PROJECT_NEW}/plot_config.yml"
echo "  5. Run the pipeline:"
echo ""
echo "     # Linux (full pipeline, conda環境内):"
echo "     conda activate rnaseq_takubo"
echo "     bash ${PIPELINE_DIR}/run_pipeline.sh --config ${PROJECT_NEW}/config.sh"
echo ""
echo "     # Windows/Mac (R解析のみ, RStudio推奨):"
echo "     cd ${PROJECT_NEW}"
echo "     Rscript ${PIPELINE_DIR}/scripts/04_deseq2.R config.sh"
echo ""
echo "======================================================"
